[project]
name = "cnn-for-rmp-image-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "efficientnet-pytorch>=0.7.1",
    "matplotlib>=3.10.3",
    "pillow>=11.3.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "wandb>=0.21.0",
]
